### PR TITLE
Improvement on loader 6

### PR DESCRIPTION
**Pull request by OxyDesign**
Improvement on circular path (location computed with `sin` & `cos`) and more/different steps to have a better transformation (closer to a real circle), as asked in #11.
I only made changes in the Less file (.css and .html are generated).
Feel free to tell me if it's not suitable.

### CODE REVIEW

**Comment by lukehaas** [comment]
Thanks for doing this, but there is currently an issue with the spacing of the box-shadows. In my original the box-shadows get a much wider spacing at the peak of the transition. This is an aspect I'd like to maintain for this loader.

**Comment by OxyDesign** [comment]
Ok I see. I changed it a little bit. Is it enough ? Thank you

**Comment by lukehaas** [comment]
Thanks again, it's just a little off still. If you imagine the loader as a clock face the peak of the transition, when the box shadows are most spaced, needs to be at 6 o'clock. Also, the box-shadows are now just a little too spaced out at their peak.

**Comment by OxyDesign** [comment]
Ok and now ?

**Comment by OxyDesign** [comment]
Thanx

**Comment by lukehaas** [comment]
Thanks for all your work on this.
I made some additional tweaks to alter the timing.

**Comment by OxyDesign** [comment]
My pleasure

**Pull request merged**
